Repository ChaSaji/PickNic, pull requests merged in 2024-06, with the labels that each got.

#144 イベント詳細ページの実装とレイアウトコンポーネントの作成
  web/src/app/events/[eventId]/edit/page.tsx
  web/src/app/events/[eventId]/page.tsx
  web/src/app/events/[eventId]/pictures/page.tsx
  web/src/app/globals.css
  web/src/app/layout.tsx
  web/src/app/page.module.css
  web/src/app/page.tsx
  web/src/components/Button/Button.tsx
  web/src/components/Header/Header.tsx
  web/src/components/PageTemplate/PageTemplate.tsx
  web/src/components/Title/Title.tsx
Labels: create ui

#146 add:APIフォルダにJSON形式のデータをレスポンスするファイル(RequestReturn.py)を追加
  api/.gitignore
  api/RequestReturn.py
Labels: enhancement

#148 ログインページとInputFieldの実装
  web/package-lock.json
  web/package.json
  web/src/app/(app)/events/[eventId]/edit/page.tsx
  web/src/app/(app)/events/[eventId]/page.tsx
  web/src/app/(app)/events/[eventId]/pictures/page.tsx
  web/src/app/(app)/layout.tsx
  web/src/app/(auth)/login/page.tsx
  web/src/app/layout.tsx
  web/src/app/page.tsx
  web/src/app/test/page.tsx
  web/src/components/Button/Button.tsx
  web/src/components/InputField/InputField.tsx
  web/src/schemas/loginSchema.ts
Labels: create ui

#158 ファイル名の変更
  api/openCV.py
  api/requestReturn.py
Labels: environment

#165 Feature/#164 seperate api directory
  api/api/__init__.py
  api/api/cruds/__init__.py
  api/api/main.py
  api/api/models/__init__.py
  api/api/routers/__init__.py
  api/api/schemes/__init__.py
  api/openCV/__init__.py
  api/openCV/openCV.py
  api/poetry.lock
  api/pyproject.toml
Labels: environment

#136 expoのver.48→51に伴うSQLlte関数のバグ修正
  nativeApp/package-lock.json
  nativeApp/package.json
  nativeApp/src/lib/dataBaseHelper.js
  nativeApp/src/lib/databaseQueryText.js
  nativeApp/src/screens/DbScreen.js
  nativeApp/src/screens/HomeScreen.js
Labels: bug

#171 イベント作成のAPIリクエストに対する処理作成
  api/api/main.py
  api/api/routers/event.py
  api/api/schemes/event.py
Labels: enhancement, environment

#180 expoのver.48→51に伴うcamera関数のバグ修正
  api/OpenCV.py
  nativeApp/.env.template
  nativeApp/.gitignore
  nativeApp/babel.config.js
  nativeApp/package-lock.json
  nativeApp/package.json
  nativeApp/src/App.js
  nativeApp/src/lib/databaseQueryText.js
  nativeApp/src/lib/sendPicture.js
  nativeApp/src/navigation/AppNavigator.js
  nativeApp/src/screens/CameraScreen.js
  nativeApp/src/screens/HomeScreen.js
Labels: bug, version_error

#163 Feature/#139 event list
  web/package-lock.json
  web/package.json
  web/src/app/(app)/events/create/page.tsx
  web/src/app/(app)/events/page.tsx
Labels: create ui

#188 Release/v1.0.0 to develop
  api/openCV/openCV.py
  nativeApp/.env.template
  nativeApp/.gitignore
  nativeApp/babel.config.js
  nativeApp/package-lock.json
  nativeApp/package.json
  nativeApp/src/App.js
  nativeApp/src/lib/dataBaseHelper.js
  nativeApp/src/lib/databaseQueryText.js
  nativeApp/src/lib/sendPicture.js
  nativeApp/src/navigation/AppNavigator.js
  nativeApp/src/screens/CameraScreen.js
  nativeApp/src/screens/DbScreen.js
  nativeApp/src/screens/HomeScreen.js
Labels: release
