Repository ChaSaji/PickNic, pull requests merged in 2024-07, with the labels that each got.

#190 モバイルのイベントタブを作成したよ
  nativeApp/assets/sample.jpg
  nativeApp/src/components/EventCard.js
  nativeApp/src/components/MyButton.js
  nativeApp/src/lib/getRandomPointInRadius.js
  nativeApp/src/lib/getScoreMessage.js
  nativeApp/src/navigation/AppNavigator.js
  nativeApp/src/navigation/stacks/EventStack.js
  nativeApp/src/screens/BadgeDetailScreen.js
  nativeApp/src/screens/CookingDetailScreen.js
  nativeApp/src/screens/Event/CameraScreen.js
  nativeApp/src/screens/Event/DetailScreen.js
  nativeApp/src/screens/Event/LoadingScreen.js
  nativeApp/src/screens/Event/MapScreen.js
  nativeApp/src/screens/Event/ResultScreen.js
  nativeApp/src/screens/Event/SubmitScreen.js
  nativeApp/src/screens/Event/TopScreen.js
  nativeApp/src/screens/PictureScreen.js
Labels: create ui

#173 UPDATE, DELETEの処理を作成
  api/api/routers/event.py
  api/api/schemes/event.py
Labels: enhancement, environment

#176 Feature/#175 open cv
  api/api/lib/__init__.py
  api/api/lib/akaze.py
  api/api/lib/convert_colors.py
  api/api/main.py
  api/api/routers/events/__init__.py
  api/api/routers/events/banana.jpg
  api/api/routers/events/match.py
  api/api/routers/picture2item.py
  api/banana.jpg
  api/poetry.lock
  api/pyproject.toml
Labels: refactoring

#211 DBマイグレート時に初期値が自動でDB内に与えられるようにした
  api/migrate_db.py
  api/poetry.lock
  api/pyproject.toml
  api/seed_data.json
Labels: environment

#213 api起動用のスクリプトファイルの作成
  api/main.py
Labels: environment

#177 入力フォームを作成したよ
  web/package-lock.json
  web/package.json
  web/src/app/(app)/events/create/page.tsx
  web/src/components/InputCoordinateField/InputCoordinateField.tsx
  web/src/components/InputDateField/InputDateField.tsx
  web/src/components/InputDescriptionField/InputDescriptionField.tsx
  web/src/components/InputField/InputField.tsx
  web/src/components/InputFileField/InputFileField.tsx
  web/src/schemas/eventSchema.ts
Labels: create ui

#220 Feature/#218 api user db
  api/api/cruds/mobile.py
  api/api/cruds/photo2user.py
  api/api/lib/makerelationship.py
  api/api/main.py
  api/api/models/database_models.py
  api/api/routers/mobile.py
  api/api/schemes/mobile.py
  api/api/schemes/photo2user.py
Labels: enhancement, environment

#198 モバイルのイベントページをAPIと繋げたよ
  api/api/lib/convert_colors.py
  api/api/routers/events/match.py
  api/api/routers/picture2item.py
  api/kuma.jpg
  nativeApp/package.json
  nativeApp/src/lib/api/event.js
  nativeApp/src/lib/api/helper.js
  nativeApp/src/lib/sendPicture.js
  nativeApp/src/lib/util/dateFormatter.js
  nativeApp/src/screens/Event/CameraScreen.js
  nativeApp/src/screens/Event/DetailScreen.js
  nativeApp/src/screens/Event/MapScreen.js
  nativeApp/src/screens/Event/ResultScreen.js
  nativeApp/src/screens/Event/SubmitScreen.js
  nativeApp/src/screens/Event/TopScreen.js
Labels: enhancement

#200 Webのログイン機能の作成
  api/seed_data.json
  web/.env.template
  web/.gitignore
  web/package-lock.json
  web/package.json
  web/src/app/(app)/events/page.tsx
  web/src/app/(auth)/login/page.tsx
  web/src/app/layout.tsx
  web/src/lib/api/ApiError.ts
  web/src/lib/api/auth.ts
  web/src/lib/api/helper.ts
  web/src/lib/auth/token.ts
  web/src/schemas/loginSchema.ts
  web/src/types/utils.ts
Labels: enhancement

#216 authとeventの統合処理，organization_idをBearer認証での取得
  api/api/cruds/auth.py
  api/api/cruds/event.py
  api/api/dependencies/auth.py
  api/api/models/auth.py
  api/api/models/database_models.py
  api/api/routers/auth.py
  api/api/routers/event.py
  api/api/schemes/auth.py
  api/api/schemes/event.py
  api/seed_data.json
Labels: environment

#229 ページ認証機能を加えたよ
  web/src/app/(app)/events/page.tsx
  web/src/app/(app)/layout.tsx
  web/src/app/(auth)/login/page.tsx
  web/src/app/layout.tsx
  web/src/components/AuthGuard/AuthGuard.tsx
  web/src/components/Header/Header.tsx
  web/src/context/AuthContext.tsx
  web/src/lib/api/auth.ts
  web/src/types/user.ts
Labels: enhancement

#232 エンドポイントの追加
  api/api/cruds/mobile.py
  api/api/routers/mobile.py
Labels: enhancement

#231 ユーザ一覧ページの作成
  api/api/cruds/auth.py
  api/api/routers/auth.py
  api/api/schemes/auth.py
  web/src/app/(app)/layout.tsx
  web/src/app/(app)/users/[userId]/page.tsx
  web/src/app/(app)/users/create/page.tsx
  web/src/app/(app)/users/page.tsx
  web/src/components/Button/Button.tsx
  web/src/components/Header/Header.tsx
  web/src/components/PageTemplate/PageTemplate.tsx
  web/src/hooks/useApiSubmit.ts
  web/src/lib/api/ApiError.ts
  web/src/lib/api/auth.ts
  web/src/lib/api/helper.ts
  web/src/lib/api/user.ts
  web/src/schemas/userSchema.ts
  web/src/types/user.ts
Labels: create ui

#237 イベント登録・更新・削除ができるようにしたよ
  api/api/routers/event.py
  api/api/schemes/event.py
  web/src/app/(app)/events/[eventId]/edit/page.tsx
  web/src/app/(app)/events/[eventId]/page.tsx
  web/src/app/(app)/events/create/page.tsx
  web/src/components/InputCoordinateField/InputCoordinateField.tsx
  web/src/components/InputDateField/InputDateField.tsx
  web/src/components/InputDescriptionField/InputDescriptionField.tsx
  web/src/components/InputFileField/InputFileField.tsx
  web/src/lib/api/event.ts
  web/src/schemas/eventSchema.ts
Labels: enhancement, create ui

#235 fix: apiエンドポイントの修正したよ
  nativeApp/src/lib/api/event.js
  nativeApp/src/screens/Event/SubmitScreen.js
Labels: bug

#244 ランキングスクリーンの作成
  api/api/cruds/photo2user.py
  api/api/routers/mobile.py
  api/seed_data.json
  nativeApp/assets/medal_bronze.png
  nativeApp/assets/medal_gold.png
  nativeApp/assets/medal_silver.png
  nativeApp/src/lib/api/event.js
  nativeApp/src/lib/images.js
  nativeApp/src/navigation/stacks/EventStack.js
  nativeApp/src/screens/Event/DetailScreen.js
  nativeApp/src/screens/Event/RankingScreen.js
Labels: enhancement, create ui

#242 モバイルから画像をアップロードしてクラウド上に保存し，パスをDB上に格納するした
  api/api/cruds/event.py
  api/api/cruds/mobile.py
  api/api/cruds/photo2user.py
  api/api/lib/upload_image_to_s3.py
  api/api/models/database_models.py
  api/api/routers/mobile.py
  api/api/schemes/auth.py
  api/api/schemes/event.py
  api/seed_data.json
  api/testfunc/getPhoto.py
Labels: enhancement

#252 モバイルからイベントに写真を投稿できるようにしたよ
  api/api/cruds/event.py
  api/api/cruds/mobile.py
  api/api/cruds/photo2user.py
  api/api/lib/upload_image_to_s3.py
  api/api/routers/event.py
  api/api/routers/mobile.py
  nativeApp/src/lib/sendPicture.js
  nativeApp/src/screens/Event/SubmitScreen.js
Labels: enhancement

#253 WebでR2に保存されている写真を閲覧できるようにしたよ
  api/seed_data.json
  web/src/app/(app)/events/[eventId]/edit/page.tsx
  web/src/app/(app)/events/[eventId]/page.tsx
  web/src/app/(app)/events/[eventId]/pictures/page.tsx
  web/src/app/(app)/events/[eventId]/pictures/test.json
  web/src/app/(app)/events/create/page.tsx
  web/src/app/api/r2/route.ts
  web/src/components/DetailImg/DetailImg.tsx
  web/src/components/InputFileField/InputFileField.tsx
  web/src/lib/api/event.ts
  web/src/lib/api/helper.ts
  web/src/lib/r2/getImage.ts
  web/src/schemas/eventSchema.ts
Labels: enhancement, create ui

#255 モバイルからイベント画像を見れるようにしたよ
  api/seed_data.json
  nativeApp/package-lock.json
  nativeApp/package.json
  nativeApp/src/lib/r2/s3.js
  nativeApp/src/screens/Event/DetailScreen.js
  nativeApp/src/screens/Event/MapScreen.js
Labels: enhancement

#257 カメラの画角を正方形にして、正解画像も浮かせてみたよ
  nativeApp/src/screens/Event/CameraScreen.js
  nativeApp/src/screens/Event/MapScreen.js
Labels: create ui

#261 ユーザ写真と比較対象の正解画像をR2から持ってこれるようにしたよ
  api/api/cruds/photo2user.py
  api/api/lib/r2/create_s3_client.py
  api/api/lib/r2/download_image_from_s3.py
  api/api/lib/r2/upload_image_to_s3.py
  api/api/main.py
  api/api/routers/event.py
  api/api/routers/events/__init__.py
  api/api/routers/events/banana.jpg
  api/api/routers/events/match.py
  api/api/routers/mobile.py
  api/banana.jpg
  api/kuma.jpg
  api/testfunc/getPhoto.py
Labels: enhancement

#263 細々した修正をしたよ
  api/api/schemes/event.py
  web/package-lock.json
  web/package.json
  web/src/app/(app)/events/[eventId]/page.tsx
  web/src/app/(app)/events/[eventId]/pictures/page.tsx
  web/src/app/(app)/events/page.tsx
  web/src/app/(app)/users/[userId]/page.tsx
  web/src/app/(app)/users/create/page.tsx
  web/src/app/(app)/users/me/edit/page.tsx
  web/src/app/(app)/users/me/page.tsx
  web/src/components/Loading/Loading.tsx
  web/src/lib/utils/formatDate.ts
Labels: create ui

#265 ユーザ画面から自分のスコアを見れるようにしたよ
  api/api/routers/mobile.py
  api/api/schemes/event.py
  nativeApp/src/lib/api/event.js
  nativeApp/src/screens/Event/DetailScreen.js
Labels: enhancement, create ui

#269 最終発表段階で動作させていた状態の反映など
  api/api/cruds/mobile.py
  api/migrate_db.py
  api/seed_data.json
  nativeApp/package-lock.json
  nativeApp/package.json
  nativeApp/src/navigation/AppNavigator.js
Labels: bug, environment
