Repository ChaSaji/PickNic, pull requests merged in 2024-03, with the labels that each got.

#12 各ページファイルの設定
  package-lock.json
  package.json
  src/App.js
  src/screens/BadgeScreen.js
  src/screens/BagScreen.js
  src/screens/CameraScreen.js
  src/screens/CookingScreen.js
  src/screens/HomeScreen.js
Labels: enhancement

#19 add: 開発プロセスのreadmeを書きました
  README.md
Labels: documentation

#24 称号画面の簡易UI作成
  src/screens/BadgeScreen.js
Labels: create ui

#35 Feature/#29 change to material bottom tabs
  src/App.js
  src/navigation/AppNavigator.js
  src/navigation/stacks/BadgeStack.js
  src/navigation/stacks/BagStack.js
  src/navigation/stacks/CookingStack.js
  src/navigation/stacks/HomeStack.js
Labels: enhancement

#38 カメラボタンのUIを軒田さんのUIに変更
  assets/icons8-camera-64.png
  src/components/CameraButton.js
  src/screens/HomeScreen.js
Labels: create ui

#43 これまでのファイル群をnativeApp下に、fastapi系をapi下に配置する想定でディレクトリ構造を変更しました。
  api/sample.py
  natiiveApp/.gitignore
  natiiveApp/README.md
  natiiveApp/app.json
  natiiveApp/assets/adaptive-icon.png
  natiiveApp/assets/favicon.png
  natiiveApp/assets/icon.png
  natiiveApp/assets/icons8-camera-64.png
  natiiveApp/assets/splash.png
  natiiveApp/babel.config.js
  natiiveApp/main.js
  natiiveApp/package-lock.json
  natiiveApp/package.json
  natiiveApp/src/App.js
  natiiveApp/src/components/CameraButton.js
  natiiveApp/src/lib/dataBaseHelper.js
  natiiveApp/src/lib/databaseQueryText.js
  natiiveApp/src/navigation/AppNavigator.js
  natiiveApp/src/navigation/stacks/BadgeStack.js
  natiiveApp/src/navigation/stacks/BagStack.js
  natiiveApp/src/navigation/stacks/CookingStack.js
  natiiveApp/src/navigation/stacks/HomeStack.js
  natiiveApp/src/screens/BadgeScreen.js
  natiiveApp/src/screens/BagScreen.js
  natiiveApp/src/screens/CameraScreen.js
  natiiveApp/src/screens/CookingScreen.js
  natiiveApp/src/screens/HomeScreen.js
Labels: environment

#47 native appのディレクトリ名をnatiiveAppからnativeAppに変更
  nativeApp/.gitignore
  nativeApp/README.md
  nativeApp/app.json
  nativeApp/assets/adaptive-icon.png
  nativeApp/assets/favicon.png
  nativeApp/assets/icon.png
  nativeApp/assets/icons8-camera-64.png
  nativeApp/assets/splash.png
  nativeApp/babel.config.js
  nativeApp/main.js
  nativeApp/package-lock.json
  nativeApp/package.json
  nativeApp/src/App.js
  nativeApp/src/components/CameraButton.js
  nativeApp/src/lib/dataBaseHelper.js
  nativeApp/src/lib/databaseQueryText.js
  nativeApp/src/navigation/AppNavigator.js
  nativeApp/src/navigation/stacks/BadgeStack.js
  nativeApp/src/navigation/stacks/BagStack.js
  nativeApp/src/navigation/stacks/CookingStack.js
  nativeApp/src/navigation/stacks/HomeStack.js
  nativeApp/src/screens/BadgeScreen.js
  nativeApp/src/screens/BagScreen.js
  nativeApp/src/screens/CameraScreen.js
  nativeApp/src/screens/CookingScreen.js
  nativeApp/src/screens/HomeScreen.js
Labels: environment

#49 Cookingの簡易版UIを作成しました．
  nativeApp/src/screens/CookingScreen.js
Labels: create ui

#55 タイマーの作成
  nativeApp/package-lock.json
  nativeApp/package.json
  nativeApp/src/components/CameraButton.js
  nativeApp/src/context/CameraContext.js
  nativeApp/src/navigation/stacks/HomeStack.js
  nativeApp/src/screens/CameraScreen.js
  nativeApp/src/screens/HomeScreen.js
Labels: enhancement

#63 bagのUIを作成しました
  nativeApp/src/navigation/AppNavigator.js
  nativeApp/src/screens/BagScreen.js
  nativeApp/src/screens/DbScreen.js
Labels: create ui

#67 初呼び出し処理の追加とDbScreenの修正
  nativeApp/src/App.js
  nativeApp/src/lib/Redme.md
  nativeApp/src/lib/dataBaseHelper.js
  nativeApp/src/screens/DbScreen.js
Labels: enhancement, environment

#65 Feature/#44fast api opencv
  api/OpenCV.py
  api/sample.py
Labels: environment

#61 クッキング画面のフローの作成
  nativeApp/assets/cooking.json
  nativeApp/assets/dev-cooking.json
  nativeApp/package-lock.json
  nativeApp/package.json
  nativeApp/src/navigation/stacks/CookingStack.js
  nativeApp/src/screens/CookingAnimationScreen.js
  nativeApp/src/screens/CookingCompleteScreen.js
  nativeApp/src/screens/CookingDetailScreen.js
  nativeApp/src/screens/CookingScreen.js
Labels: create ui

#59 カメラを撮ってからのマテリアル取得までのフローを作成
  nativeApp/src/components/ChangeMaterialButton.js
  nativeApp/src/context/CameraContext.js
  nativeApp/src/context/GetMaterialContext.js
  nativeApp/src/navigation/stacks/HomeStack.js
  nativeApp/src/screens/CameraScreen.js
  nativeApp/src/screens/GetMaterialScreen.js
  nativeApp/src/screens/PictureScreen.js
Labels: create ui

#72 画像を送信すると色の情報が返ってきます．
  nativeApp/package-lock.json
  nativeApp/package.json
  nativeApp/src/lib/sendPicture.js
  nativeApp/src/screens/PictureScreen.js
  package-lock.json
Labels: enhancement

#75 カレーの画像
  nativeApp/assets/badge.png
  nativeApp/assets/beef.png
  nativeApp/assets/carrot.png
  nativeApp/assets/curry.png
  nativeApp/assets/onion.png
  nativeApp/assets/potato.png
Labels: create ui

#89 変換したアイテムを表示、DBに反映
  nativeApp/src/App.js
  nativeApp/src/context/DbUpdateContext.js
  nativeApp/src/context/GetMaterialContext.js
  nativeApp/src/lib/dataBaseHelper.js
  nativeApp/src/lib/databaseQueryText.js
  nativeApp/src/lib/getRandomNum.js
  nativeApp/src/navigation/stacks/HomeStack.js
  nativeApp/src/screens/BagScreen.js
  nativeApp/src/screens/CameraScreen.js
  nativeApp/src/screens/CookingDetailScreen.js
  nativeApp/src/screens/GetMaterialScreen.js
  nativeApp/src/screens/PictureScreen.js
Labels: enhancement, high priority

#91 ロック状態とアンクックド状態の表示を作成
  nativeApp/assets/lock.png
  nativeApp/src/components/ItemCard.js
  nativeApp/src/lib/images.js
  nativeApp/src/screens/BadgeDetailScreen.js
  nativeApp/src/screens/BadgeScreen.js
  nativeApp/src/screens/BagScreen.js
  nativeApp/src/screens/CookingCompleteScreen.js
  nativeApp/src/screens/CookingDetailScreen.js
  nativeApp/src/screens/CookingScreen.js
Labels: create ui, high priority

#93 add: API通信時のローディング画面へのページ遷移作成
  nativeApp/src/lib/sendPicture.js
  nativeApp/src/navigation/stacks/HomeStack.js
  nativeApp/src/screens/GetMaterialScreen.js
  nativeApp/src/screens/HomeScreen.js
  nativeApp/src/screens/LoadingAnimationScreen.js
  nativeApp/src/screens/PictureScreen.js
  nativeApp/src/screens/SubmitToAPIScreen.js
Labels: create ui

#79 撮った写真をDBに登録
  nativeApp/src/components/PictureMarker.js
  nativeApp/src/context/CameraContext.js
  nativeApp/src/context/DbUpdateContext.js
  nativeApp/src/context/LocationContext.js
  nativeApp/src/navigation/stacks/HomeStack.js
  nativeApp/src/screens/CameraScreen.js
  nativeApp/src/screens/HomeScreen.js
  nativeApp/src/screens/PictureViewScreen.js
Labels: enhancement, create ui, high priority

#105 複数回マテリアルが更新されてしまうバグの修正
  nativeApp/src/navigation/stacks/HomeStack.js
  nativeApp/src/screens/GetMaterialScreen.js
  nativeApp/src/screens/PictureScreen.js
  nativeApp/src/screens/SubmitToAPIScreen.js
Labels: bug, high priority

#123 コピーライトスクリーンの作成
  nativeApp/src/components/InformationButton.js
  nativeApp/src/navigation/stacks/HomeStack.js
  nativeApp/src/screens/CopyrightScreen.js
  nativeApp/src/screens/HomeScreen.js
Labels: high priority

#130 バッジの表示の修正、ダミーバッジの追加
  dbInittool/excels/Badge.xlsx
  dbInittool/excels/MealStatus.xlsx
  nativeApp/src/lib/dataBaseInit.js
  nativeApp/src/screens/BadgeDetailScreen.js
  nativeApp/src/screens/BadgeScreen.js
Labels: create ui
